services:
  gitbackup:
    container_name: gitbackup
    hostname: gitbackup
    image: gitbackup
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: "no"
    volumes:
      - /tmp/git-backup:/tmp/git-backup
      - ./config.json5:/app/config.json5