services:
  git_backup:
    container_name: git_backup
    hostname: git_backup
    image: git_backup
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: "no"
    volumes:
      - /tmp:/tmp
      - ./config.jsonc:/app/config.jsonc