services:
  gitlab:
    container_name: gitlab
    hostname: gitlab
    image: 'gitlab/gitlab-ce:16.11.5-ce.0'
    restart: always
    environment:
      TZ: Europe/Athens
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.domain.org'
    ports:
      - '8022:22'
    volumes:
      - './gitlab-config:/etc/gitlab'
      - './gitlab-logs:/var/log/gitlab'
      - './gitlab-data:/var/opt/gitlab'

  dufs:
    container_name: dufs
    hostname: dufs
    image: sigoden/dufs:v0.40.0
    restart: 'always'
    command: /data -A
    stdin_open: true
    tty: true
    environment:
      TZ: Europe/Athens
    volumes:
      - ./dufs-data:/data
